import { useState, type FormEvent } from 'react'
import { useApp } from '../context/AppContext'
import { Button, Card, Empty, Field, Input, PageHeader, Select } from '../components/ui'
import type { Area, CatalogItem, Company } from '../types'

export function SettingsPage() {
  const { data, updateData, session } = useApp()
  const [company, setCompany] = useState('')
  const [area, setArea] = useState({ name: '', companyId: '' })
  const [catalog, setCatalog] = useState({ name: '', kind: 'Puesto' as CatalogItem['kind'] })
  const timestamp = () => new Date().toISOString()
  const canEdit = session?.role === 'Administrador'
  const addCompany = (event: FormEvent) => { event.preventDefault(); const item: Company = { id: crypto.randomUUID(), name: company.trim(), active: true, createdAt: timestamp(), updatedAt: timestamp() }; updateData('companies', [...data.companies, item], 'Crear', item.id, undefined, item); setCompany('') }
  const addArea = (event: FormEvent) => { event.preventDefault(); const item: Area = { id: crypto.randomUUID(), ...area, active: true, createdAt: timestamp(), updatedAt: timestamp() }; updateData('areas', [...data.areas, item], 'Crear', item.id, undefined, item); setArea({ name: '', companyId: '' }) }
  const addCatalog = (event: FormEvent) => { event.preventDefault(); const item: CatalogItem = { id: crypto.randomUUID(), ...catalog, active: true, createdAt: timestamp(), updatedAt: timestamp() }; updateData('catalog', [...data.catalog, item], 'Crear', item.id, undefined, item); setCatalog({ ...catalog, name: '' }) }
  const toggle = (module: 'companies' | 'areas' | 'catalog', id: string) => { const current = data[module].find((entry) => entry.id === id); const next = data[module].map((entry) => entry.id === id ? { ...entry, active: !entry.active, updatedAt: timestamp() } : entry); updateData(module, next, current?.active ? 'Desactivar' : 'Activar', id, current, next.find((entry) => entry.id === id)) }
  return <><PageHeader title="Configuración" description="Catálogos abiertos y configurables. Los registros se desactivan, no se eliminan." />{!canEdit && <p className="mb-4 rounded-lg bg-amber-50 p-3 text-sm text-amber-800">Solo el Administrador puede modificar catálogos.</p>}<div className="grid gap-5 xl:grid-cols-3">
    <Card><h2 className="font-bold">Empresas</h2><form className="my-4 flex gap-2" onSubmit={addCompany}><Input value={company} onChange={(e) => setCompany(e.target.value)} placeholder="Nombre" required disabled={!canEdit} /><Button disabled={!canEdit}>Agregar</Button></form>{data.companies.length ? <ul className="space-y-2">{data.companies.map((entry) => <li key={entry.id} className="flex items-center justify-between rounded-lg bg-slate-50 p-3"><span>{entry.name}</span><Button variant="ghost" disabled={!canEdit} onClick={() => toggle('companies', entry.id)}>{entry.active ? 'Desactivar' : 'Activar'}</Button></li>)}</ul> : <Empty />}</Card>
    <Card><h2 className="font-bold">Áreas</h2><form className="my-4 grid gap-2" onSubmit={addArea}><Field label="Empresa"><Select required value={area.companyId} onChange={(e) => setArea({ ...area, companyId: e.target.value })} disabled={!canEdit}><option value="">Seleccione</option>{data.companies.filter((entry) => entry.active).map((entry) => <option key={entry.id} value={entry.id}>{entry.name}</option>)}</Select></Field><Input value={area.name} onChange={(e) => setArea({ ...area, name: e.target.value })} placeholder="Nombre del área" required disabled={!canEdit} /><Button disabled={!canEdit}>Agregar</Button></form>{data.areas.length ? <ul className="space-y-2">{data.areas.map((entry) => <li key={entry.id} className="flex items-center justify-between rounded-lg bg-slate-50 p-3"><span>{entry.name}</span><Button variant="ghost" disabled={!canEdit} onClick={() => toggle('areas', entry.id)}>{entry.active ? 'Desactivar' : 'Activar'}</Button></li>)}</ul> : <Empty />}</Card>
    <Card><h2 className="font-bold">Otros catálogos</h2><form className="my-4 grid gap-2" onSubmit={addCatalog}><Select value={catalog.kind} onChange={(e) => setCatalog({ ...catalog, kind: e.target.value as CatalogItem['kind'] })} disabled={!canEdit}><option>Puesto</option><option>Centro de costo</option><option>Tipo de trabajo</option><option>Proyecto</option><option>Tipo de planilla</option></Select><Input value={catalog.name} onChange={(e) => setCatalog({ ...catalog, name: e.target.value })} placeholder="Nombre" required disabled={!canEdit} /><Button disabled={!canEdit}>Agregar</Button></form>{data.catalog.length ? <ul className="space-y-2">{data.catalog.map((entry) => <li key={entry.id} className="flex items-center justify-between rounded-lg bg-slate-50 p-3"><span><small className="block text-slate-500">{entry.kind}</small>{entry.name}</span><Button variant="ghost" disabled={!canEdit} onClick={() => toggle('catalog', entry.id)}>{entry.active ? 'Desactivar' : 'Activar'}</Button></li>)}</ul> : <Empty />}</Card>
  </div></>
}
